Release 2.5.0 (#135)
* Set a test API key (the one in the API call examples from OWM API website)

* Try to fix Travis Virtualenv support for Py32

* Fix again

* Bump to version 2.3.1

* Don't commit coverage file

* Dockerfile (#106)

* First attempt

* Guide

* Fix Dockerfile and docs

* Update docs

* Change URL of documentation to comply with new readthedocs domain

* Backporting from master branch

* Refactor integration tests to use the API key specified in api_key.py

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Messed up with Git... sunrise/sunset fix from #109 is OK now

* Sometimes Wind data is None

Hello !
I'm useing Homeassistant, and sometimes I got the following error:
```
Traceback (most recent call last):
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 98, in _setup_platform
    discovery_info)
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 70, in setup_platform
    dev.append(OpenWeatherMapSensor(data, variable, unit))
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 94, in __init__
    self.update()
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 114, in update
    self.owa_client.update()
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 289, in wrapper
    result = method(*args, **kwargs)
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 179, in update
    self.longitude)
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/owm25.py", line 432, in three_hours_forecast_at_coords
    forecast = self._parsers['forecast'].parse_JSON(json_data)
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/forecastparser.py", line 66, in parse_JSON
    for item in d['list']]
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/forecastparser.py", line 66, in <listcomp>
    for item in d['list']]
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/weather.py", line 462, in weather_from_dictionary
    wind = d['wind'].copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

This patch fixes this error

* Regression test for #110

* update with new contributor

* Fixes for #110 and  #114

* Forgot...

* Were missing

* Bump to version 2.3.2

* How to install multiple python versions

* Feature/#100 python34 support (#118)

* Fix failing test on py32

* update

* fix wrong command

* Ran all tests against Python3.4 and Python3.5 using tox

* Forgot to align Travis as well

* added weather_history_at_coords (#89)

* Add txemi and sorted alphabetically

* Unit tests for method: weather_history_at_coords

* A bit too much stuff passed in as params :-p

* Feature/#121 datetime switch (#122)

* A bit too much stuff passed in as params :-p

* Now you can get reference/reception times as Python datetime.datetime objects as well

* Update

* hoorayyy!

* Added support for unicode place names (#86)

* Update

* Better checks for visibility distance - credits to @dstmar

* Feature/#112 weather by ids (#123)

* improve test that sometimes fails (on very busy machines)

* Added OWM25 method "weather_at_ids"

* Vast refactoring

* Update city ID files and prepare for release 2.4.0

* Back ported from master branch

* Slack team

* Possible fix for Unicode names (#127)

* Update link to OWM API docs

* Add timezone info (#128)

* tests and doc for string/unicode-handling functions in OWM25

* Feature/#93 uv index api (#131)

* New entity: UVIndex, along with unit tests and XMLNS

* New exception for 401 erorrs

* JSON parser for UVIndex instances

* More utils: last_month, last_year, next_month, next_year

* Add "interval" attribute to UVIndex

* Wired new HTTP client for UV API subset; a bit of refactoring

* tests for uvindex_around_coords

* Add missing location to print

* Better exception handling

* Intergation test

* Ooops

* Feature/#129 air pollution api (#134)

* COIndex entity and tests

* Change XML schema and fix tests

* Fix CO sample key: had to be "value" instead of "vmr"

* COIndexParser and test

* Typo

* HTTP Air Pollution data client and tests

* cut 'n' paste leftovers

* Refactoring: we're getting too verbose, man!

* More refactoring

* OWM method for polling CO and test

* Fix docs

* Fix mess about reception_time: now UVIndex entities have both a reference_time and a reception_time

* Same fix: reference_time and reception_time are now available (with proper semantic) on COIndex

* Add is_forecast method to COIndex

* fix test

* cleaner

* Ozone entity and OzoneParser

* Integation tests updated with air pollution airpoints check

* Add ozone_around_coords method to OWM25 and patched tests along

* Fix bug: it was failing due to missing location sting

* Better exception raising

* Improved some integration tests

* better indentation

* Slight change

* Update version, prepare for dumping version

* Remove dead code

* Docstring fixes

* Fix docstrings more

* Fix erorr