Release 2.4.0 (#124)
* Set a test API key (the one in the API call examples from OWM API website)

* Try to fix Travis Virtualenv support for Py32

* Fix again

* Bump to version 2.3.1

* Don't commit coverage file

* Dockerfile (#106)

* First attempt

* Guide

* Fix Dockerfile and docs

* Update docs

* Change URL of documentation to comply with new readthedocs domain

* Backporting from master branch

* Refactor integration tests to use the API key specified in api_key.py

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Fix ValueError then sunrise_time & sunset time is less than zero when there is a polar day

* Messed up with Git... sunrise/sunset fix from #109 is OK now

* Sometimes Wind data is None

Hello !
I'm useing Homeassistant, and sometimes I got the following error:
```
Traceback (most recent call last):
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 98, in _setup_platform
    discovery_info)
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 70, in setup_platform
    dev.append(OpenWeatherMapSensor(data, variable, unit))
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 94, in __init__
    self.update()
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 114, in update
    self.owa_client.update()
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 289, in wrapper
    result = method(*args, **kwargs)
  File "/home/titilambert/gits/domo/homeassitant/env/lib/python3.4/site-packages/homeassistant/components/sensor/openweathermap.py", line 179, in update
    self.longitude)
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/owm25.py", line 432, in three_hours_forecast_at_coords
    forecast = self._parsers['forecast'].parse_JSON(json_data)
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/forecastparser.py", line 66, in parse_JSON
    for item in d['list']]
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/forecastparser.py", line 66, in <listcomp>
    for item in d['list']]
  File "/home/titilambert/gits/domo/homeassitant/config/deps/pyowm/webapi25/weather.py", line 462, in weather_from_dictionary
    wind = d['wind'].copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

This patch fixes this error

* Regression test for #110

* update with new contributor

* Fixes for #110 and  #114

* Forgot...

* Were missing

* Bump to version 2.3.2

* How to install multiple python versions

* Feature/#100 python34 support (#118)

* Fix failing test on py32

* update

* fix wrong command

* Ran all tests against Python3.4 and Python3.5 using tox

* Forgot to align Travis as well

* added weather_history_at_coords (#89)

* Add txemi and sorted alphabetically

* Unit tests for method: weather_history_at_coords

* A bit too much stuff passed in as params :-p

* Feature/#121 datetime switch (#122)

* A bit too much stuff passed in as params :-p

* Now you can get reference/reception times as Python datetime.datetime objects as well

* Update

* hoorayyy!

* Added support for unicode place names (#86)

* Update

* Better checks for visibility distance - credits to @dstmar

* Feature/#112 weather by ids (#123)

* improve test that sometimes fails (on very busy machines)

* Added OWM25 method "weather_at_ids"

* Vast refactoring

* Update city ID files and prepare for release 2.4.0